
version: "3.8"
services:
  ibmmq:
    image: ibmcom/mq:latest
    container_name: ibmmq
    ports:
      - "1414:1414"
      - "9443:9443"
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_APP_PASSWORD: passw0rd
    volumes:
      - mqdata:/mnt/mqm
      - ./config.mqsc:/etc/mqm/config.mqsc
    command: >
      bash -c "echo 'Running MQSC...' &&
               /opt/mqm/bin/strmqm QM1 &&
               /opt/mqm/bin/runmqsc QM1 < /etc/mqm/config.mqsc &&
               tail -f /dev/null"

volumes:
  mqdata:
